### ISSUE TITLE
掉落物清理的物品保存到垃圾桶

### ISSUE THREAD

**Issue by luoyei365** [4o4E/EClean#10]
版本和核心和标题一致，在使用指令执行立即清除程序之后清除的物品没有出现在垃圾桶，建议把垃圾桶添添加个新模式【里面清除的物品会保存到下一次清除程序执行】可以通过配置文件或者指令在两种模式中切换

**Comment by 4o4E** [comment]
暂时没有精力更新这个

**Comment by luoyei365** [comment]
> 

好吧，等你更新

**Comment by 4o4E** [comment]
https://github.com/4o4E/EClean/releases/tag/1.17.0

已更新
