### ISSUE TITLE
限制实体清理是否有问题？

### ISSUE THREAD

**Issue by 164ebr** [4o4E/EClean#12]
Paper - 1.20.1
EClean v1.16.1
![image](https://github.com/4o4E/EClean/assets/86980013/0a4f3e56-32e4-4f49-9e8b-3ae38926ec28)
配置文件
![image](https://github.com/4o4E/EClean/assets/86980013/e0bec2b8-31bb-491e-a482-ccdae3efb737)

目光所及之处不止三只村民，为什么限制清理规则不生效呢

**Comment by 4o4E** [comment]
[EClean-1.16.1.zip](https://github.com/4o4E/EClean/files/12728046/EClean-1.16.1.zip)
尝试该版本

**Comment by 4o4E** [comment]
https://github.com/4o4E/EClean/releases/tag/1.17.0
