### ISSUE TITLE
清理时有可能清理quickshop的物品展示到垃圾桶里面

### ISSUE THREAD

**Issue by hseermc** [4o4E/EClean#15]
如图
![image](https://github.com/4o4E/EClean/assets/143265074/57cab039-730d-41e4-81ba-405519204262)
那么长的一坨就是quickshop插件中展示的物品中的一个
![image](https://github.com/4o4E/EClean/assets/143265074/cf4c3841-8d1b-4c88-bec0-811952e8f697)

**Comment by 4o4E** [comment]
quickshop配置文件中的display-type可以切换虚拟显示
