### ISSUE TITLE
最新版EClean不运行清理

### ISSUE THREAD

**Issue by m1919810** [4o4E/EClean#19]
我正在使用EClean1.18.0
并没有出现掉落物清理提示 也没有进行掉落物清除
同样的配置文件我换上EClean1.16.0即可正常运行

**Comment by m1919810** [comment]
版本1.20.1和1.20.4测试中均不运行

**Comment by 4o4E** [comment]
实际测试是会正常清理的, 删除配置文件重新生成再试试
