### ISSUE TITLE
在ChestCommands菜单打开垃圾桶时出问题

### ISSUE THREAD

**Issue by orangeZSCB** [4o4E/EClean#2]
如题

**Comment by 4o4E** [comment]
描述具体问题

**Comment by orangeZSCB** [comment]
我在ChestCommands设置了一个菜单，然后我在这个菜单的某一格设置了“垃圾桶”选项，指令就是正常打开垃圾桶的指令，然后当我尝试在游戏中点击这个选项，EClean只会在聊天框内打出：垃圾桶 关闭后…… 类的字。但是并没有正常打开垃圾桶。
我尝试将gm的默认身分组加上eclean.trash的权限，但是使用另一个账号（没有op）打开后依然还是上面的状况。
麻烦帮忙解决，谢谢！

**Comment by 4o4E** [comment]
> 我在ChestCommands设置了一个菜单，然后我在这个菜单的某一格设置了“垃圾桶”选项，指令就是正常打开垃圾桶的指令，然后当我尝试在游戏中点击这个选项，EClean只会在聊天框内打出：垃圾桶 关闭后…… 类的字。但是并没有正常打开垃圾桶。
> 我尝试将gm的默认身分组加上eclean.trash的权限，但是使用另一个账号（没有op）打开后依然还是上面的状况。
> 麻烦帮忙解决，谢谢！

先关闭菜单，然后再使用指令

**Comment by orangeZSCB** [comment]
我关闭了CC菜单使用了指令，生效了。
但是我在CC菜单内使用指令，失败了。


_回复好快啊……_

**Comment by 4o4E** [comment]
> 我关闭了CC菜单使用了指令，生效了。
> 但是我在CC菜单内使用指令，失败了。
> 
> 
> _回复好快啊……_

让你在脚本里面写一个延时，先关闭菜单，然后再给玩家执行指令

**Comment by orangeZSCB** [comment]
哦懂了懂了 谢谢 有事再找您 麻烦啦
