### ISSUE TITLE
无法正常清理垃圾

### ISSUE THREAD

**Issue by LectWolf** [4o4E/EClean#20]
版本1.18.0
无法正常进行玩家清理
没有玩家在线的时候进行垃圾清理

看了下源码,这里的修改意思是
玩家不在线时 noOnline为true吧

然后配置设置不在线不清理的 且 没玩家在线 时候 开始清理

![24388dbc46df9436f1633476db5455c0](https://github.com/4o4E/EClean/assets/67421358/848e96cd-64ee-435d-949e-5238fbe81794)

![95ca19626620bc1719d85373f39419b9](https://github.com/4o4E/EClean/assets/67421358/9dc0e75f-fce7-4b37-ab6b-4503da2c7539)

**Comment by 4o4E** [comment]
https://github.com/4o4E/EClean/releases/tag/1.18.1
