### ISSUE TITLE
1.12.2版本测试中不清理岩浆怪

### ISSUE THREAD

**Issue by NeglectDream** [4o4E/EClean#23]
Eclean version: 1.16.1

在eclean show里面显示的岩浆怪右键也删不掉，希望修复
(java8什么时候好)

**Comment by 4o4E** [comment]
> Eclean version: 1.16.1
> 
> 在eclean show里面显示的岩浆怪右键也删不掉，希望修复 (java8什么时候好)

`/eclean debug`开启debug模式后查看日志，点击按钮时是否有日志？

java8不是我代码的问题，是上游依赖的问题，我也无能为力
