### ISSUE TITLE
白名单设置

### ISSUE THREAD

**Issue by Yamada993** [4o4E/EClean#7]
配置文件似乎没有明确的标注白名单或黑名单添加方式，如何进行添加呢？如果有gui方式那就更好了

**Comment by 4o4E** [comment]
> 配置文件似乎没有明确的标注白名单或黑名单添加方式，如何进行添加呢？如果有gui方式那就更好了

https://github.com/4o4E/EClean/blob/main/src/main/resources/config.yml#L46

**Comment by Yamada993** [comment]
# 若设置为true则按黑名单匹配(名字匹配的才清理)
  # 若设置为false则按白名单匹配(名字匹配的不清理)
  is_black: true
  我已经设置了该设置，但是白名单如何设置呢？
  还有就是垃圾桶用菜单打开（op模式）却没有任何上次清扫的记录

**Comment by 4o4E** [comment]
垃圾桶不是名字就写了不保留物品吗

**Comment by 4o4E** [comment]
白名单就是下面的match

**Comment by Yamada993** [comment]
好的白名单问题已经解决，那么垃圾桶是如何工作的？描述中写道关闭后销毁物品，但是再初次打开垃圾桶却无法看见任何被清理的垃圾

**Comment by 4o4E** [comment]
销毁了你怎么再看到物品？

**Comment by Yamada993** [comment]
我似乎明白垃圾桶是什么意思了，大概是主动把要销毁的东西放进垃圾桶，然后关闭页面后自动消除所有东西？
对了白名单的设置中match添加的是物品类型，那么可以根据物品id或者元数据之类的匹配单个物品吗？

**Comment by Yamada993** [comment]
> 我似乎明白垃圾桶是什么意思了，大概是主动把要销毁的东西放进垃圾桶，然后关闭页面后自动消除所有东西？ 对了白名单的设置中match添加的是物品类型，那么可以根据物品id或者元数据之类的匹配单个物品吗？

如果添加了mod，那么似乎添加方式会更复杂？

**Comment by 4o4E** [comment]
没有任何支持mod相关内容的计划

**Comment by 4o4E** [comment]
match你看上下文啊，那是实体清理的部分，和物品有什么关系

**Comment by 4o4E** [comment]
match里面的物品，是掉落物的清理规则

**Comment by Yamada993** [comment]
我是指清理玩家使用的掉落物，部分mod中需要玩家将物品以掉落物的方式丢在地上或者丢在某种液体中进行合成等操作，部分合成花费时间较长，我在配置文件中看到有关掉落物的清理方式：
https://github.com/4o4E/EClean/blob/c1921c89dac0e0fd5036d95cd37900aabe7e9deb/src/main/resources/config.yml#L85
这里是只支持原版掉落物吗？

**Comment by 4o4E** [comment]
> 没有任何支持mod相关内容的计划

**Comment by Yamada993** [comment]
好的那么问题已经结束，我已经了解了，谢谢！
